/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kennethtzh (https://sketchfab.com/kennethtzh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dae-villages-shipwrecked-chinese-supply-store-af2da248227c4dac96fc2570e58e26da
Title: DAE Villages | Shipwrecked Chinese Supply Store
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame, useThree} from '@react-three/fiber'
import {a} from '@react-spring/three'

import shipWreck from '../assets/3d/shipWreck.glb'

const Ship =(props)=> {
    const shipRef = useRef()

  const { nodes, materials } = useGLTF(shipWreck)
  return (
    <a.group ref={shipRef} {...props}>
      <mesh               
        geometry={nodes.pCylinder109_sky_m_0.geometry}
        material={materials.sky_m}
        position={[38.813, 111.873, -63.188]}
        rotation={[Math.PI / 2, 0, 0.094]}
        scale={[70.228, 67.648, 70.228]}
      />
      <mesh               
        geometry={nodes.group144_textureAtlas_m_0.geometry}
        material={materials.textureAtlas_m}
      />
      <mesh               
        geometry={nodes.group144_environmentAtlas_m_0.geometry}
        material={materials.environmentAtlas_m}
      />
    </a.group>
  )
}


export default Ship;